name: word_puzzles
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.0.0
  shared_preferences: ^2.0.11
  audioplayers: ^6.0.0
  mutex: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.2

flutter:
  uses-material-design: true

  assets:
    - assets/dictionaries/commonWords.txt
    - assets/dictionaries/extraWords.txt
    - assets/dictionaries/badWords.txt
    - assets/themes/default.json
    - assets/audio/bonk.mp3
    - assets/audio/click1.mp3
    - assets/audio/ding.mp3
    - assets/audio/pop.mp3
